"""Auto-generate the Pareto plot from JSON outputs of run_supervised.py.

Scans checkpoints/sup_*.json, aggregates by method (mean ± std across seeds),
plots final_avg accuracy vs capacity (% bits remaining), and writes:
  - figures/pareto.pdf (paper figure)
  - figures/pareto.png (preview)
  - tables/main.tex (main results LaTeX table)

Usage: python analysis/pareto_from_json.py [--ckpt_dir checkpoints]
"""
from __future__ import annotations
import os, sys, json, argparse, glob
from collections import defaultdict
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import numpy as np

# Style: ACL-ish, no matplotlib defaults
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
plt.rcParams.update({
    'font.family': 'serif', 'font.size': 11,
    'axes.labelsize': 12, 'axes.titlesize': 12,
    'legend.fontsize': 9, 'figure.dpi': 150,
    'axes.spines.top': False, 'axes.spines.right': False,
})

METHOD_STYLE = {
    'finetune': {'label': 'Finetune',   'color': '#888888', 'marker': 'x'},
    'replay':   {'label': 'ER (replay)', 'color': '#4CAF50', 'marker': 's'},
    'der':      {'label': 'DER++',       'color': '#9C27B0', 'marker': 'D'},
    'ewc':      {'label': 'EWC',         'color': '#795548', 'marker': 'v'},
    'mas':      {'label': 'MAS',         'color': '#FF9800', 'marker': '^'},
    'packnet':  {'label': 'PackNet',     'color': '#E91E63', 'marker': 'P'},
    'csc':      {'label': 'CSC (ours)',  'color': '#1565C0', 'marker': 'o'},
}


def load_results(ckpt_dir: str, dataset: str = 'cifar100') -> dict:
    """Group JSON results by (method, num_tasks), filtered to a single dataset."""
    groups = defaultdict(list)
    for f in sorted(glob.glob(os.path.join(ckpt_dir, 'sup_*.json'))):
        try:
            with open(f) as fh:
                d = json.load(fh)
        except Exception as e:
            print(f'  skip {f}: {e}'); continue
        cfg = d.get('config', {})
        # Backward-compat: old JSONs without 'dataset' key are CIFAR-100
        ds = cfg.get('dataset', 'cifar100')
        if ds != dataset:
            continue
        key = (cfg.get('method', 'unknown'), cfg.get('num_tasks', 0))
        groups[key].append(d)
    return groups


def aggregate(rows: list[dict]) -> dict:
    """Aggregate seeds: return mean/std of final_avg, bwt, bits_remaining."""
    if not rows:
        return {}
    accs = np.array([r['final_avg'] for r in rows]) * 100
    bwts = np.array([r['bwt'] for r in rows]) * 100
    bits = np.array([(r.get('compression') or {}).get('compression_ratio', 1.0)
                     for r in rows]) * 100
    return {
        'n': len(rows),
        'acc_mean': accs.mean(), 'acc_std': accs.std(ddof=0) if len(accs) > 1 else 0.0,
        'bwt_mean': bwts.mean(), 'bwt_std': bwts.std(ddof=0) if len(bwts) > 1 else 0.0,
        'bits_mean': bits.mean(), 'bits_std': bits.std(ddof=0) if len(bits) > 1 else 0.0,
    }


def make_pareto_plot(groups: dict, num_tasks: int, out_pdf: str, out_png: str):
    fig, ax = plt.subplots(figsize=(6.5, 4.5))
    for (method, nt), rows in sorted(groups.items()):
        if nt != num_tasks:
            continue
        agg = aggregate(rows)
        if not agg:
            continue
        style = METHOD_STYLE.get(method, {'label': method, 'color': 'k', 'marker': 'o'})
        ax.errorbar(agg['bits_mean'], agg['acc_mean'],
                    xerr=agg['bits_std'], yerr=agg['acc_std'],
                    fmt=style['marker'], color=style['color'], markersize=11,
                    label=f"{style['label']} (n={agg['n']})",
                    capsize=3, linewidth=1.4, markeredgecolor='black',
                    markeredgewidth=0.5)
    ax.set_xlabel('Capacity used (% of 32-bit precision)')
    ax.set_ylabel('Avg accuracy across all tasks (%)')
    ax.set_title(f'Split CIFAR-100, {num_tasks} tasks')
    ax.set_xlim(-3, 110)
    ax.set_ylim(20, 95)
    ax.grid(alpha=0.25)
    # "better" hint in corner pointing up-left
    ax.annotate('', xy=(5, 92), xytext=(25, 80),
                arrowprops=dict(arrowstyle='->', color='#666666', lw=1.2))
    ax.text(15, 82, 'better', color='#666666', fontsize=9, rotation=35,
            ha='center', va='center')
    ax.legend(loc='lower right', frameon=True, ncol=1)
    plt.tight_layout()
    fig.savefig(out_pdf); fig.savefig(out_png, dpi=200)
    plt.close(fig)
    print(f'Wrote: {out_pdf}\nWrote: {out_png}')


def make_results_table(groups: dict, num_tasks: int, out_tex: str):
    rows = []
    for (method, nt), runs in groups.items():
        if nt != num_tasks: continue
        agg = aggregate(runs)
        if not agg: continue
        style = METHOD_STYLE.get(method, {'label': method})
        rows.append((style['label'], method, agg))
    # Sort: baselines first (highest bits), then csc
    rows.sort(key=lambda r: (-r[2]['bits_mean'], r[1]))
    with open(out_tex, 'w') as f:
        f.write('% Auto-generated by analysis/pareto_from_json.py\n')
        f.write('\\begin{tabular}{lrrrr}\n\\toprule\n')
        f.write('Method & Avg Acc (\\%) & BWT (\\%) & Bits (\\%) & $n$ \\\\\n')
        f.write('\\midrule\n')
        for label, _method, agg in rows:
            f.write(f'{label} & '
                    f'${agg["acc_mean"]:.2f} \\pm {agg["acc_std"]:.2f}$ & '
                    f'${agg["bwt_mean"]:+.2f} \\pm {agg["bwt_std"]:.2f}$ & '
                    f'${agg["bits_mean"]:.1f}$ & {agg["n"]} \\\\\n')
        f.write('\\bottomrule\n\\end{tabular}\n')
    print(f'Wrote: {out_tex}')


def main():
    p = argparse.ArgumentParser()
    p.add_argument('--ckpt_dir', default='checkpoints')
    p.add_argument('--out_dir', default='csc_paper')
    p.add_argument('--num_tasks', type=int, default=10)
    p.add_argument('--dataset', default='cifar100', choices=['cifar100', 'pmnist'])
    args = p.parse_args()

    os.makedirs(os.path.join(args.out_dir, 'figures'), exist_ok=True)
    os.makedirs(os.path.join(args.out_dir, 'tables'), exist_ok=True)

    groups = load_results(args.ckpt_dir, dataset=args.dataset)
    print(f'Found {sum(len(v) for v in groups.values())} runs across '
          f'{len(groups)} (method, num_tasks) groups.')
    for k, v in sorted(groups.items()):
        print(f'  {k}: n={len(v)}')

    suffix = '' if args.dataset == 'cifar100' else f'_{args.dataset}'
    make_pareto_plot(groups, args.num_tasks,
                     os.path.join(args.out_dir, 'figures', f'pareto{suffix}.pdf'),
                     os.path.join(args.out_dir, 'figures', f'pareto{suffix}.png'))
    make_results_table(groups, args.num_tasks,
                       os.path.join(args.out_dir, 'tables', f'main{suffix}.tex'))


if __name__ == '__main__':
    main()
