"""Aggregate Continual World final-success JSONs into a method × seed table.

Usage:  python analysis/rl_summary.py [--ckpt_dir checkpoints]
Reads checkpoints/cw_<method>_<tasks>_s<seed>[<tag>]_final.json and prints
per-method mean success / forgetting + writes csc_paper/tables/rl.tex.
"""
from __future__ import annotations
import os, sys, json, glob, argparse
from collections import defaultdict
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import numpy as np

DISPLAY = {
    'finetune':   'Finetune',
    'l2':         'L2',
    'ewc':        'EWC',
    'mas':        'MAS',
    'replay':     'ER',
    'replay_shared': 'ER (shared $\\alpha$)',
    'csc':        'CSC (replay)',
    'csc_shared': 'CSC (replay, shared $\\alpha$)',
    'clonex':     'ClonEx-SAC',
    'csc_clonex': 'CSC + BC distill',
    'packnet':    'PackNet',
    'ewc_replay': 'EWC + ER',
}

ORDER = ['finetune', 'l2', 'ewc', 'mas', 'replay', 'replay_shared',
         'csc', 'csc_shared', 'clonex', 'csc_clonex',
         'ewc_replay', 'packnet']


def load(ckpt_dir: str, tasks_filter: str = 'cw_subset'):
    by = defaultdict(list)
    for f in sorted(glob.glob(os.path.join(ckpt_dir, 'cw_*_final.json'))):
        d = json.load(open(f))
        cfg = d['config']
        if cfg.get('tasks') != tasks_filter:
            continue
        method = cfg['method']
        # Distinguish shared_alpha runs by tag
        if cfg.get('tag') == '_shared' and method in ('replay', 'csc'):
            method = method + '_shared'
        by[method].append({
            'avg': d['avg'],
            'final': d['final'],
            'seed': cfg['seed'],
        })
    return by


def main():
    p = argparse.ArgumentParser()
    p.add_argument('--ckpt_dir', default='checkpoints')
    p.add_argument('--tasks', default='cw_subset')
    p.add_argument('--out_tex', default='csc_paper/tables/rl.tex')
    args = p.parse_args()

    by = load(args.ckpt_dir, args.tasks)
    print(f'Continual World ({args.tasks}) — final success aggregate\n')
    print(f"{'Method':<32s}  {'n':>3s}  {'avg ± std':>14s}  {'best':>5s}  {'min':>5s}")
    print('-' * 72)
    rows = []
    for m in ORDER:
        if m not in by:
            continue
        vals = np.array([100 * x['avg'] for x in by[m]])
        line = (f"{DISPLAY.get(m, m):<32s}  {len(vals):>3d}  "
                f"{vals.mean():>5.2f} ± {vals.std():>5.2f}    "
                f"{vals.max():>5.2f}  {vals.min():>5.2f}")
        print(line)
        rows.append((m, vals))

    if rows and args.out_tex:
        os.makedirs(os.path.dirname(args.out_tex), exist_ok=True)
        with open(args.out_tex, 'w') as f:
            f.write('% auto-generated by analysis/rl_summary.py\n')
            f.write('\\begin{tabular}{lcc}\n\\toprule\n')
            f.write('Method & $n$ seeds & Avg.\\ success (\\%) \\\\\n\\midrule\n')
            for m, vals in rows:
                f.write(f'{DISPLAY.get(m, m)} & {len(vals)} & '
                        f'${vals.mean():.2f} \\pm {vals.std():.2f}$ \\\\\n')
            f.write('\\bottomrule\n\\end{tabular}\n')
        print(f'\nWrote: {args.out_tex}')


if __name__ == '__main__':
    main()
